# python producer from 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: s3-twitter-producer
  namespace: stream
spec:
  selector:
    matchLabels:
      app: producer
  replicas: 1
  template:
    metadata:
      name: s3-twitter-producer
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: liouvetren/s3twitterproducer:latest
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 500m
            memory: 1024Mi
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-pass
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-pass
              key: secretkey
        # readinessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /tmp/healthy
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        command:
        - sh
        - -c
        - "exec tail -f /dev/null"
        # command: 
        # - python
        # - /app/app.py
        # - s3://data-pool-liouvetren
        # - 2017/12/22/00/00
        # - 2017/12/22/00/02
        # - kafka.kafka:9092
        # - twitterdata
        # - "0.001"
# python /twitterproducer/app.py s3://data-pool-liouvetren 2017/12/22/00/00 2017/12/22/01/10 kafka.kafka:9092 twitterdata 

